name: "ci"
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-tests:
    runs-on: ubuntu-latest
    name: Check Tests
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6

      - name: run tests
        run: dotnet test
