name: "godot-ci export"
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game
    timeout-minutes: 30
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
  
    - name: export game
      id: export
      uses: firebelley/godot-export@v5.2.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_export_templates.tpz
        relative_project_path: ./
        cache: true
        archive_output: true

    - name: Upload Windows
      uses: actions/upload-artifact@v1
      with:
        name: windows
        path: /home/runner/.local/share/godot/archives/Windows Desktop.zip

    - name: Upload Linux
      uses: actions/upload-artifact@v1
      with:
        name: linux
        path: /home/runner/.local/share/godot/archives/LinuxX11.zip

    - name: Upload MacOS
      uses: actions/upload-artifact@v1
      with:
        name: macos
        path: /home/runner/.local/share/godot/archives/macOS.zip
